/** @type {import('tailwindcss').Config} */
// Design system. Colours are CSS variables (src/theme.css, generated by
// scripts/gen-theme.mjs) so every class renders in both day and night.
// New UI should prefer the semantic names (bg-surface, text-muted-foreground,
// bg-primary …); the palette names keep existing markup on-system.
const SHADES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950']
const PALETTES = [
  'slate', 'brand', 'emerald', 'amber', 'red', 'rose', 'blue', 'indigo', 'violet', 'cyan',
  'sky', 'orange', 'yellow', 'green', 'teal', 'purple', 'pink',
]
const v = (name) => `rgb(var(--${name}) / <alpha-value>)`
const palettes = Object.fromEntries(PALETTES.map((p) => [
  p, Object.fromEntries(SHADES.map((s) => [s, v(`${p}-${s}`)])),
]))

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        ...palettes,
        background: v('background'),
        foreground: v('foreground'),
        sidebar: v('sidebar'),
        surface: { DEFAULT: v('surface'), elevated: v('surface-elevated'), muted: v('surface-muted') },
        border: { DEFAULT: v('border'), subtle: v('border-subtle') },
        primary: { DEFAULT: v('primary'), hover: v('primary-hover'), foreground: v('primary-foreground') },
        secondary: { DEFAULT: v('secondary'), foreground: v('secondary-foreground') },
        muted: { DEFAULT: v('muted'), foreground: v('muted-foreground') },
        success: v('success'),
        warning: v('warning'),
        error: v('error'),
        info: v('info'),
      },
      fontFamily: {
        // System UI first (SF Pro on Apple, Segoe UI Variable on Windows),
        // Inter as the cross-platform fallback.
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"Segoe UI Variable Text"', '"Segoe UI"',
               'Inter', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', '"SF Mono"', '"Cascadia Mono"', 'Menlo', 'Consolas',
               '"Liberation Mono"', 'monospace'],
      },
      // Calmer weights: "bold" reads as confident, not shouty.
      fontWeight: { medium: '500', semibold: '580', bold: '640', extrabold: '700' },
      // Tighter tracking as size grows; generous line-height at small sizes.
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.005em' }],
        xs:    ['0.75rem',   { lineHeight: '1.125rem' }],
        sm:    ['0.8125rem', { lineHeight: '1.25rem' }],
        base:  ['0.9375rem', { lineHeight: '1.5rem', letterSpacing: '-0.005em' }],
        lg:    ['1.0625rem', { lineHeight: '1.5rem',  letterSpacing: '-0.01em' }],
        xl:    ['1.25rem',   { lineHeight: '1.75rem', letterSpacing: '-0.014em' }],
        '2xl': ['1.5rem',    { lineHeight: '2rem',    letterSpacing: '-0.018em' }],
        '3xl': ['1.875rem',  { lineHeight: '2.25rem', letterSpacing: '-0.022em' }],
        '4xl': ['2.25rem',   { lineHeight: '2.5rem',  letterSpacing: '-0.026em' }],
        '5xl': ['3rem',      { lineHeight: '1',       letterSpacing: '-0.03em' }],
      },
      // Less rounded overall — precise, not bubbly.
      borderRadius: { sm: '4px', DEFAULT: '5px', md: '6px', lg: '8px', xl: '10px', '2xl': '12px', '3xl': '16px' },
      boxShadow: { sm: 'var(--shadow-sm)', md: 'var(--shadow-md)', lg: 'var(--shadow-lg)', xl: 'var(--shadow-lg)', '2xl': 'var(--shadow-lg)' },
    },
  },
  plugins: [],
}
